# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('geotemporal-library', ['internet'])
    module.source = [
        'model/geotemporal-utils.cc',
        'model/gps-system.cc',
        'model/graph-utils.cc',
        'model/math-utils.cc',
        'model/packet-utils.cc',
        'model/path-utils.cc',
        'model/statistics-utils.cc',
        'model/string-utils.cc',
        'model/vehicle-routes.cc',
        ]

    # module_test = bld.create_ns3_module_test_library('geotemporal-library')
    # module_test.source = [
    #     'test/geotemporal-library-test-suite.cc',
    #     ]

    headers = bld(features='ns3header')
    headers.module = 'geotemporal-library'
    headers.source = [
        'model/geotemporal-utils.h',
        'model/gps-system.h',
        'model/graph-utils.h',
        'model/math-utils.h',
        'model/packet-utils.h',
        'model/path-utils.h',
        'model/statistics-utils.h',
        'model/string-utils.h',
        'model/vehicle-routes.h',
        ]

    # if bld.env.ENABLE_EXAMPLES:
    #     bld.recurse('examples')

    # bld.ns3_python_bindings()

