# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('geotemporal-restricted-epidemic-example',
                                 ['internet', 'wifi', 'wave', 'geotemporal-library',
                                 'geotemporal-restricted-epidemic'])
    obj.source = [
        'geotemporal-restricted-epidemic-example.cc',
        'geotemporal-restricted-epidemic-application.cc',
        'geotemporal-restricted-epidemic-installer.cc',
        ]

