# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('geotemporal', ['internet', 'wifi'])
    module.source = [
        'model/geotemporal-duplicate-detector.cc',
        'model/geotemporal-neighbors-table.cc',
        'model/geotemporal-packets-queue.cc',
        'model/geotemporal-packets.cc',
        'model/geotemporal-routing-protocol.cc',
        'helper/geotemporal-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('geotemporal')
    module_test.source = [
        'test/geotemporal-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'geotemporal'
    headers.source = [
        'model/geotemporal-duplicate-detector.h',
        'model/geotemporal-neighbors-table.h',
        'model/geotemporal-packets-queue.h',
        'model/geotemporal-packets.h',
        'model/geotemporal-routing-protocol.h',
        'helper/geotemporal-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

