# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('geotemporal-epidemic', ['internet', 'wifi'])
    module.source = [
        'model/geotemporal-epidemic-duplicate-detector.cc',
        'model/geotemporal-epidemic-neighbors-table.cc',
        'model/geotemporal-epidemic-packets-queue.cc',
        'model/geotemporal-epidemic-packets.cc',
        'model/geotemporal-epidemic-routing-protocol.cc',
        'helper/geotemporal-epidemic-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('geotemporal-epidemic')
    module_test.source = [
        'test/geotemporal-epidemic-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'geotemporal-epidemic'
    headers.source = [
        'model/geotemporal-epidemic-duplicate-detector.h',
        'model/geotemporal-epidemic-neighbors-table.h',
        'model/geotemporal-epidemic-packets-queue.h',
        'model/geotemporal-epidemic-packets.h',
        'model/geotemporal-epidemic-routing-protocol.h',
        'helper/geotemporal-epidemic-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

