# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('geotemporal-spray-and-wait-example',
                                 ['internet', 'wifi', 'wave', 'geotemporal-library',
                                 'geotemporal-spray-and-wait'])
    obj.source = [
        'geotemporal-spray-and-wait-example.cc',
        'geotemporal-spray-and-wait-application.cc',
        'geotemporal-spray-and-wait-installer.cc',
        ]

